baseURL = 'http://onlymattjohnson.com/'
languageCode = 'en-us'
title = 'Matt Johnson'
theme = 'archie'

[permalinks]
    posts= '/:year/:month/:day/:title/'

[params]
    mode="auto"
    useCDN=false

[[params.social]]
name="GitHub"
icon="github"
url="https://github.com/onlymattjohnson"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2